export enum AutomationMode {
    AUTOMATION_MODE_UNSPECIFIED = "AUTOMATION_MODE_UNSPECIFIED",
    AUTO_CREATE_PR = "AUTO_CREATE_PR",
}

export enum SessionState {
    STATE_UNSPECIFIED = "STATE_UNSPECIFIED",
    QUEUED = "QUEUED",
    PLANNING = "PLANNING",
    AWAITING_PLAN_APPROVAL = "AWAITING_PLAN_APPROVAL",
    AWAITING_USER_FEEDBACK = "AWAITING_USER_FEEDBACK",
    IN_PROGRESS = "IN_PROGRESS",
    PAUSED = "PAUSED",
    FAILED = "FAILED",
    COMPLETED = "COMPLETED",
}
